services:
  backend: 
    build: .
    ports: 
    - 5000:5000
    - 9029:9029
    volumes: 
    - .:/usr/src/app
    - /usr/src/app/node_modules
    command: npm run start:docker
    environment:
      PORT: 5000

